### ISSUE TITLE
Support for scoped storage or when app targets Android 10 and above

### ISSUE THREAD

**Issue by VikasJilla** [bonamoogy/FolderFileSaver#3]
The [Android developer documentation](https://developer.android.com/reference/android/os/Environment#getExternalStorageDirectory()) says the below method is deprecated
`Environment.getExternalStorageDirectory()`

**Comment by VikasJilla** [comment]
Please add support for the apps targeting API level 29 and more

**Comment by bonamoogy** [comment]
Hey @VikasJilla package has been updated. check it out.

Thanks!
